openapi: 3.0.0
info:
  title: HeNex V3 Copy
  description: This collection includes all the APIs of version 3 for HeNex
  version: 1.0.0
servers:
  - url: https://api.diem-platform.com
paths:
  /api/v3/data/henexmarketresultsborderschedules/2021/10/29/2:
    get:
      tags:
        - General
      summary: GR Market-Market Results BorderSchedules
      operationId:  GR Market-Market Results BorderSchedules
      description: 
      x-codegen-request-body-name: rest_service14request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service14request"
            example:
              interconnection: AL-GR
              direction: 0
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketresultsborderschedules/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Results BorderSchedules
      operationId:  GR Market-PreMarket Results BorderSchedules
      description: 
      x-codegen-request-body-name: rest_service39request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service39request"
            example:
              direction: 0
              interconnection: AL-GR
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketresultsdemand/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Results Demand
      operationId:  GR Market-PreMarket Results Demand
      description: 
      x-codegen-request-body-name: rest_service63request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service63request"
            example:
              direction: 1
              class: LV
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketsummaryperproductiontechnology/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Summary per Production Technology
      operationId:  GR Market-PreMarket Summary per Production Technology
      description: 
      x-codegen-request-body-name: rest_service88request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service88request"
            example:
              direction: 0
              technology: Lignite
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/interconnections/TR:
    get:
      tags:
        - General
      summary: interconnections/interconnection Copy
      operationId:  interconnections/interconnection Copy
      description: 
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
              example:
                value: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
              example:
                value: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
              example:
                value: Origin, X-Requested-With, Content-Type, Accept, x-auth-token
            Access-Control-Allow-Methods:
              schema:
                type: string
              example:
                value: POST, GET, PUT, DELETE, OPTIONS
            Content-Type:
              schema:
                type: string
              example:
                value: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example:
                value: '6670'
            ETag:
              schema:
                type: string
              example:
                value: W/"1a0e-9I8LOehKXu48HrJX99GxUthlJcc"
            Date:
              schema:
                type: string
              example:
                value: Mon, 13 Mar 2023 12:53:59 GMT
            Connection:
              schema:
                type: string
              example:
                value: keep-alive
            Keep-Alive:
              schema:
                type: string
              example:
                value: timeout=5
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/rest_serviceResponse176"
              example:
                $schema: http://json-schema.org/draft-04/schema#
                type: array
                items:
                  type: object
                  properties:
                    TGInterconnectionName:
                      type: string
                    interconnectionAbbrev:
                      type: string
                    InAreaRefName:
                      type: string
                    InAreaRefAbbrev:
                      type: string
                    OutAreaRefName:
                      type: string
                    OutAreaRefAbbrev:
                      type: string
                  required:
                    - TGInterconnectionName
                    - interconnectionAbbrev
                    - InAreaRefName
                    - InAreaRefAbbrev
                    - OutAreaRefName
                    - OutAreaRefAbbrev
components:
  schemas:
     rest_service14request:
       type: object
       properties: 
         interconnection: 
           $ref: "#/components/schemas/Dependency1"
         direction: 
           type:  string
         market: 
           type:  string
     rest_service39request:
       type: object
       properties: 
         direction: 
           type:  string
         interconnection: 
           $ref: "#/components/schemas/Dependency1"
     rest_service63request:
       type: object
       properties: 
         direction: 
           type:  string
         class: 
           type:  string
         market: 
           type:  string
     rest_service88request:
       type: object
       properties: 
         direction: 
           type:  string
         technology: 
           type:  string
         market: 
           type:  string
     rest_serviceResponse176:
       type: object
       properties: 
         example: 
           $ref: "#/components/schemas/rest_serviceResponse176_example"
     rest_serviceResponse176_example:
       type: object
       properties: 
         items: 
           $ref: "#/components/schemas/rest_serviceResponse176_items"
     rest_serviceResponse176_items:
       type: object
       properties: 
         TGInterconnectionName: 
           type:  string
         interconnectionAbbrev: 
           $ref: "#/components/schemas/Dependency1"
         InAreaRefName: 
           type:  string
         InAreaRefAbbrev: 
           type:  string
         OutAreaRefName: 
           type:  string
         OutAreaRefAbbrev: 
           type:  string
     Dependency1:
       type: object
       properties:
         CONTENT:
           type:  string
